"""Markdown helpers for the generated data quality report.

Each pipeline step owns one section of docs/data_quality_report.md, delimited by
HTML comment markers, and replaces only that section when it re-runs.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import pandas as pd

from src.config import DOCS_DIR

REPORT_PATH = DOCS_DIR / "data_quality_report.md"
REPORT_HEADER = (
    "# Data Quality Report\n\n"
    "_Generated by the pipeline. Each section is rewritten by the step that owns it "
    "(profiling, cleaning, validation); do not edit by hand._\n"
)


def md_table(headers: list[str], rows: list[list[Any]]) -> str:
    def cell(value: Any) -> str:
        if value is None or (isinstance(value, float) and pd.isna(value)):
            return "-"
        if isinstance(value, bool):
            return str(value)
        if isinstance(value, int):
            return f"{value:,}"
        return str(value).replace("|", "\\|")

    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(cell(v) for v in row) + " |" for row in rows]
    return "\n".join(lines)


def frame_to_md(df: pd.DataFrame) -> str:
    rows = [[v.item() if hasattr(v, "item") else v for v in row] for row in df.itertuples(index=False)]
    return md_table(df.columns.tolist(), rows)


def write_report_section(key: str, content: str, path: Path = REPORT_PATH) -> None:
    """Insert or replace the section identified by `key` in the report."""
    begin, end = f"<!-- BEGIN {key} -->", f"<!-- END {key} -->"
    block = f"{begin}\n{content.strip()}\n{end}"

    text = path.read_text(encoding="utf-8") if path.exists() else REPORT_HEADER
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pattern.search(text):
        text = pattern.sub(lambda _: block, text)
    else:
        text = text.rstrip() + "\n\n" + block + "\n"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
